<?php

namespace Modules\Localization\Database\Seeders;

use Illuminate\Database\Seeder;
use Illuminate\Database\Eloquent\Model;
use Modules\Localization\Repositories\CountryRepository;

class CountryTableSeeder extends Seeder
{
    /**
     * @var CountryRepository
     */
    private $country;

    public function __construct(CountryRepository $country)
    {

        $this->country = $country;
    }

    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
        Model::unguard();
        $countries = [
            ['iso' => 'TR', 'tr' => ['name' => 'Türkiye']],
            ['iso' => 'AF', 'tr' => ['name' => 'Afganistan']],
            ['iso' => 'AX', 'tr' => ['name' => 'Aland Adaları']],
            ['iso' => 'DE', 'tr' => ['name' => 'Almanya']],
            ['iso' => 'US', 'tr' => ['name' => 'Amerika Birleşik Devletleri']],
            ['iso' => 'UM', 'tr' => ['name' => 'Amerika Birleşik Devletleri Küçük Dış Adaları']],
            ['iso' => 'AS', 'tr' => ['name' => 'Amerikan Samoası']],
            ['iso' => 'VI', 'tr' => ['name' => 'ABD Virgin Adaları']],
            ['iso' => 'AD', 'tr' => ['name' => 'Andorra']],
            ['iso' => 'AO', 'tr' => ['name' => 'Angola']],
            ['iso' => 'AI', 'tr' => ['name' => 'Anguilla']],
            ['iso' => 'AQ', 'tr' => ['name' => 'Antarktika']],
            ['iso' => 'AG', 'tr' => ['name' => 'Antigua ve Barbuda']],
            ['iso' => 'AR', 'tr' => ['name' => 'Arjantin']],
            ['iso' => 'AL', 'tr' => ['name' => 'Arnavutluk']],
            ['iso' => 'AW', 'tr' => ['name' => 'Aruba']],
            ['iso' => 'AU', 'tr' => ['name' => 'Avustralya']],
            ['iso' => 'AT', 'tr' => ['name' => 'Avusturya']],
            ['iso' => 'AZ', 'tr' => ['name' => 'Azerbaycan']],
            ['iso' => 'BS', 'tr' => ['name' => 'Bahamalar']],
            ['iso' => 'BH', 'tr' => ['name' => 'Bahreyn']],
            ['iso' => 'BD', 'tr' => ['name' => 'Bangladeş']],
            ['iso' => 'BB', 'tr' => ['name' => 'Barbados']],
            ['iso' => 'EH', 'tr' => ['name' => 'Batı Sahara']],
            ['iso' => 'BZ', 'tr' => ['name' => 'Belize']],
            ['iso' => 'BE', 'tr' => ['name' => 'Belçika']],
            ['iso' => 'BJ', 'tr' => ['name' => 'Benin']],
            ['iso' => 'BM', 'tr' => ['name' => 'Bermuda']],
            ['iso' => 'BY', 'tr' => ['name' => 'Beyaz Rusya']],
            ['iso' => 'BT', 'tr' => ['name' => 'Bhutan']],
            ['iso' => 'ZZ', 'tr' => ['name' => 'Bilinmeyen veya Geçersiz Bölge']],
            ['iso' => 'AE', 'tr' => ['name' => 'Birleşik Arap Emirlikleri']],
            ['iso' => 'GB', 'tr' => ['name' => 'Birleşik Krallık']],
            ['iso' => 'BO', 'tr' => ['name' => 'Bolivya']],
            ['iso' => 'BA', 'tr' => ['name' => 'Bosna Hersek']],
            ['iso' => 'BW', 'tr' => ['name' => 'Botsvana']],
            ['iso' => 'BV', 'tr' => ['name' => 'Bouvet Adası']],
            ['iso' => 'BR', 'tr' => ['name' => 'Brezilya']],
            ['iso' => 'BN', 'tr' => ['name' => 'Brunei']],
            ['iso' => 'BG', 'tr' => ['name' => 'Bulgaristan']],
            ['iso' => 'BF', 'tr' => ['name' => 'Burkina Faso']],
            ['iso' => 'BI', 'tr' => ['name' => 'Burundi']],
            ['iso' => 'CV', 'tr' => ['name' => 'Cape Verde']],
            ['iso' => 'KY', 'tr' => ['name' => 'Cayman Adaları']],
            ['iso' => 'GI', 'tr' => ['name' => 'Cebelitarık']],
            ['iso' => 'DZ', 'tr' => ['name' => 'Cezayir']],
            ['iso' => 'CX', 'tr' => ['name' => 'Christmas Adası']],
            ['iso' => 'DJ', 'tr' => ['name' => 'Cibuti']],
            ['iso' => 'CC', 'tr' => ['name' => 'Cocos Adaları']],
            ['iso' => 'CK', 'tr' => ['name' => 'Cook Adaları']],
            ['iso' => 'DK', 'tr' => ['name' => 'Danimarka']],
            ['iso' => 'DO', 'tr' => ['name' => 'Dominik Cumhuriyeti']],
            ['iso' => 'DM', 'tr' => ['name' => 'Dominika']],
            ['iso' => 'TL', 'tr' => ['name' => 'Doğu Timor']],
            ['iso' => 'EC', 'tr' => ['name' => 'Ekvador']],
            ['iso' => 'GQ', 'tr' => ['name' => 'Ekvator Ginesi']],
            ['iso' => 'SV', 'tr' => ['name' => 'El Salvador']],
            ['iso' => 'ID', 'tr' => ['name' => 'Endonezya']],
            ['iso' => 'ER', 'tr' => ['name' => 'Eritre']],
            ['iso' => 'AM', 'tr' => ['name' => 'Ermenistan']],
            ['iso' => 'EE', 'tr' => ['name' => 'Estonya']],
            ['iso' => 'ET', 'tr' => ['name' => 'Etiyopya']],
            ['iso' => 'FK', 'tr' => ['name' => 'Falkland Adaları']],
            ['iso' => 'FO', 'tr' => ['name' => 'Faroe Adaları']],
            ['iso' => 'MA', 'tr' => ['name' => 'Fas']],
            ['iso' => 'FJ', 'tr' => ['name' => 'Fiji']],
            ['iso' => 'CI', 'tr' => ['name' => 'Fildişi Sahili']],
            ['iso' => 'PH', 'tr' => ['name' => 'Filipinler']],
            ['iso' => 'PS', 'tr' => ['name' => 'Filistin Bölgesi']],
            ['iso' => 'FI', 'tr' => ['name' => 'Finlandiya']],
            ['iso' => 'FR', 'tr' => ['name' => 'Fransa']],
            ['iso' => 'GF', 'tr' => ['name' => 'Fransız Guyanası']],
            ['iso' => 'TF', 'tr' => ['name' => 'Fransız Güney Bölgeleri']],
            ['iso' => 'PF', 'tr' => ['name' => 'Fransız Polinezyası']],
            ['iso' => 'GA', 'tr' => ['name' => 'Gabon']],
            ['iso' => 'GM', 'tr' => ['name' => 'Gambiya']],
            ['iso' => 'GH', 'tr' => ['name' => 'Gana']],
            ['iso' => 'GN', 'tr' => ['name' => 'Gine']],
            ['iso' => 'GW', 'tr' => ['name' => 'Gine-Bissau']],
            ['iso' => 'GD', 'tr' => ['name' => 'Grenada']],
            ['iso' => 'GL', 'tr' => ['name' => 'Grönland']],
            ['iso' => 'GP', 'tr' => ['name' => 'Guadeloupe']],
            ['iso' => 'GU', 'tr' => ['name' => 'Guam']],
            ['iso' => 'GT', 'tr' => ['name' => 'Guatemala']],
            ['iso' => 'GG', 'tr' => ['name' => 'Guernsey']],
            ['iso' => 'GY', 'tr' => ['name' => 'Guyana']],
            ['iso' => 'ZA', 'tr' => ['name' => 'Güney Afrika']],
            ['iso' => 'GS', 'tr' => ['name' => 'Güney Georgia ve Güney Sandwich Adaları']],
            ['iso' => 'KR', 'tr' => ['name' => 'Güney Kore']],
            ['iso' => 'CY', 'tr' => ['name' => 'Güney Kıbrıs Rum Kesimi']],
            ['iso' => 'GE', 'tr' => ['name' => 'Gürcistan']],
            ['iso' => 'HT', 'tr' => ['name' => 'Haiti']],
            ['iso' => 'HM', 'tr' => ['name' => 'Heard Adası ve McDonald Adaları']],
            ['iso' => 'IN', 'tr' => ['name' => 'Hindistan']],
            ['iso' => 'IO', 'tr' => ['name' => 'Hint Okyanusu İngiliz Bölgesi']],
            ['iso' => 'NL', 'tr' => ['name' => 'Hollanda']],
            ['iso' => 'AN', 'tr' => ['name' => 'Hollanda Antilleri']],
            ['iso' => 'HN', 'tr' => ['name' => 'Honduras']],
            ['iso' => 'HK', 'tr' => ['name' => 'Hong Kong SAR - Çin']],
            ['iso' => 'HR', 'tr' => ['name' => 'Hırvatistan']],
            ['iso' => 'IQ', 'tr' => ['name' => 'Irak']],
            ['iso' => 'JM', 'tr' => ['name' => 'Jamaika']],
            ['iso' => 'JP', 'tr' => ['name' => 'Japonya']],
            ['iso' => 'JE', 'tr' => ['name' => 'Jersey']],
            ['iso' => 'KH', 'tr' => ['name' => 'Kamboçya']],
            ['iso' => 'CM', 'tr' => ['name' => 'Kamerun']],
            ['iso' => 'CA', 'tr' => ['name' => 'Kanada']],
            ['iso' => 'ME', 'tr' => ['name' => 'Karadağ']],
            ['iso' => 'QA', 'tr' => ['name' => 'Katar']],
            ['iso' => 'KZ', 'tr' => ['name' => 'Kazakistan']],
            ['iso' => 'KE', 'tr' => ['name' => 'Kenya']],
            ['iso' => 'KI', 'tr' => ['name' => 'Kiribati']],
            ['iso' => 'CO', 'tr' => ['name' => 'Kolombiya']],
            ['iso' => 'KM', 'tr' => ['name' => 'Komorlar']],
            ['iso' => 'CG', 'tr' => ['name' => 'Kongo - Brazavil']],
            ['iso' => 'CD', 'tr' => ['name' => 'Kongo - Kinşasa']],
            ['iso' => 'CR', 'tr' => ['name' => 'Kosta Rika']],
            ['iso' => 'KW', 'tr' => ['name' => 'Kuveyt']],
            ['iso' => 'KP', 'tr' => ['name' => 'Kuzey Kore']],
            ['iso' => 'MP', 'tr' => ['name' => 'Kuzey Mariana Adaları']],
            ['iso' => 'KK', 'tr' => ['name' => 'Kuzey Kıbrıs Türk Cumhuriyeti']],
            ['iso' => 'CU', 'tr' => ['name' => 'Küba']],
            ['iso' => 'KG', 'tr' => ['name' => 'Kırgızistan']],
            ['iso' => 'LA', 'tr' => ['name' => 'Laos']],
            ['iso' => 'LS', 'tr' => ['name' => 'Lesotho']],
            ['iso' => 'LV', 'tr' => ['name' => 'Letonya']],
            ['iso' => 'LR', 'tr' => ['name' => 'Liberya']],
            ['iso' => 'LY', 'tr' => ['name' => 'Libya']],
            ['iso' => 'LI', 'tr' => ['name' => 'Liechtenstein']],
            ['iso' => 'LT', 'tr' => ['name' => 'Litvanya']],
            ['iso' => 'LB', 'tr' => ['name' => 'Lübnan']],
            ['iso' => 'LU', 'tr' => ['name' => 'Lüksemburg']],
            ['iso' => 'HU', 'tr' => ['name' => 'Macaristan']],
            ['iso' => 'MG', 'tr' => ['name' => 'Madagaskar']],
            ['iso' => 'MO', 'tr' => ['name' => 'Makao S.A.R. Çin']],
            ['iso' => 'MK', 'tr' => ['name' => 'Makedonya']],
            ['iso' => 'MW', 'tr' => ['name' => 'Malavi']],
            ['iso' => 'MV', 'tr' => ['name' => 'Maldivler']],
            ['iso' => 'MY', 'tr' => ['name' => 'Malezya']],
            ['iso' => 'ML', 'tr' => ['name' => 'Mali']],
            ['iso' => 'MT', 'tr' => ['name' => 'Malta']],
            ['iso' => 'IM', 'tr' => ['name' => 'Man Adası']],
            ['iso' => 'MH', 'tr' => ['name' => 'Marshall Adaları']],
            ['iso' => 'MQ', 'tr' => ['name' => 'Martinik']],
            ['iso' => 'MU', 'tr' => ['name' => 'Mauritius']],
            ['iso' => 'YT', 'tr' => ['name' => 'Mayotte']],
            ['iso' => 'MX', 'tr' => ['name' => 'Meksika']],
            ['iso' => 'FM', 'tr' => ['name' => 'Mikronezya Federal Eyaletleri']],
            ['iso' => 'MD', 'tr' => ['name' => 'Moldova']],
            ['iso' => 'MC', 'tr' => ['name' => 'Monako']],
            ['iso' => 'MS', 'tr' => ['name' => 'Montserrat']],
            ['iso' => 'MR', 'tr' => ['name' => 'Moritanya']],
            ['iso' => 'MZ', 'tr' => ['name' => 'Mozambik']],
            ['iso' => 'MN', 'tr' => ['name' => 'Moğolistan']],
            ['iso' => 'MM', 'tr' => ['name' => 'Myanmar']],
            ['iso' => 'EG', 'tr' => ['name' => 'Mısır']],
            ['iso' => 'NA', 'tr' => ['name' => 'Namibya']],
            ['iso' => 'NR', 'tr' => ['name' => 'Nauru']],
            ['iso' => 'NP', 'tr' => ['name' => 'Nepal']],
            ['iso' => 'NE', 'tr' => ['name' => 'Nijer']],
            ['iso' => 'NG', 'tr' => ['name' => 'Nijerya']],
            ['iso' => 'NI', 'tr' => ['name' => 'Nikaragua']],
            ['iso' => 'NU', 'tr' => ['name' => 'Niue']],
            ['iso' => 'NF', 'tr' => ['name' => 'Norfolk Adası']],
            ['iso' => 'NO', 'tr' => ['name' => 'Norveç']],
            ['iso' => 'CF', 'tr' => ['name' => 'Orta Afrika Cumhuriyeti']],
            ['iso' => 'PK', 'tr' => ['name' => 'Pakistan']],
            ['iso' => 'PW', 'tr' => ['name' => 'Palau']],
            ['iso' => 'PA', 'tr' => ['name' => 'Panama']],
            ['iso' => 'PG', 'tr' => ['name' => 'Papua Yeni Gine']],
            ['iso' => 'PY', 'tr' => ['name' => 'Paraguay']],
            ['iso' => 'PE', 'tr' => ['name' => 'Peru']],
            ['iso' => 'PN', 'tr' => ['name' => 'Pitcairn']],
            ['iso' => 'PL', 'tr' => ['name' => 'Polonya']],
            ['iso' => 'PT', 'tr' => ['name' => 'Portekiz']],
            ['iso' => 'PR', 'tr' => ['name' => 'Porto Riko']],
            ['iso' => 'RE', 'tr' => ['name' => 'Reunion']],
            ['iso' => 'RO', 'tr' => ['name' => 'Romanya']],
            ['iso' => 'RW', 'tr' => ['name' => 'Ruanda']],
            ['iso' => 'RU', 'tr' => ['name' => 'Rusya Federasyonu']],
            ['iso' => 'BL', 'tr' => ['name' => 'Saint Barthelemy']],
            ['iso' => 'SH', 'tr' => ['name' => 'Saint Helena']],
            ['iso' => 'KN', 'tr' => ['name' => 'Saint Kitts ve Nevis']],
            ['iso' => 'LC', 'tr' => ['name' => 'Saint Lucia']],
            ['iso' => 'MF', 'tr' => ['name' => 'Saint Martin']],
            ['iso' => 'PM', 'tr' => ['name' => 'Saint Pierre ve Miquelon']],
            ['iso' => 'VC', 'tr' => ['name' => 'Saint Vincent ve Grenadinler']],
            ['iso' => 'WS', 'tr' => ['name' => 'Samoa']],
            ['iso' => 'SM', 'tr' => ['name' => 'San Marino']],
            ['iso' => 'ST', 'tr' => ['name' => 'Sao Tome ve Principe']],
            ['iso' => 'SN', 'tr' => ['name' => 'Senegal']],
            ['iso' => 'SC', 'tr' => ['name' => 'Seyşel Adaları']],
            ['iso' => 'SL', 'tr' => ['name' => 'Sierra Leone']],
            ['iso' => 'SG', 'tr' => ['name' => 'Singapur']],
            ['iso' => 'SK', 'tr' => ['name' => 'Slovakya']],
            ['iso' => 'SI', 'tr' => ['name' => 'Slovenya']],
            ['iso' => 'SB', 'tr' => ['name' => 'Solomon Adaları']],
            ['iso' => 'SO', 'tr' => ['name' => 'Somali']],
            ['iso' => 'LK', 'tr' => ['name' => 'Sri Lanka']],
            ['iso' => 'SD', 'tr' => ['name' => 'Sudan']],
            ['iso' => 'SR', 'tr' => ['name' => 'Surinam']],
            ['iso' => 'SY', 'tr' => ['name' => 'Suriye']],
            ['iso' => 'SA', 'tr' => ['name' => 'Suudi Arabistan']],
            ['iso' => 'SJ', 'tr' => ['name' => 'Svalbard ve Jan Mayen']],
            ['iso' => 'SZ', 'tr' => ['name' => 'Svaziland']],
            ['iso' => 'RS', 'tr' => ['name' => 'Sırbistan']],
            ['iso' => 'CS', 'tr' => ['name' => 'Sırbistan-Karadağ']],
            ['iso' => 'TJ', 'tr' => ['name' => 'Tacikistan']],
            ['iso' => 'TZ', 'tr' => ['name' => 'Tanzanya']],
            ['iso' => 'TH', 'tr' => ['name' => 'Tayland']],
            ['iso' => 'TW', 'tr' => ['name' => 'Tayvan']],
            ['iso' => 'TG', 'tr' => ['name' => 'Togo']],
            ['iso' => 'TK', 'tr' => ['name' => 'Tokelau']],
            ['iso' => 'TO', 'tr' => ['name' => 'Tonga']],
            ['iso' => 'TT', 'tr' => ['name' => 'Trinidad ve Tobago']],
            ['iso' => 'TN', 'tr' => ['name' => 'Tunus']],
            ['iso' => 'TC', 'tr' => ['name' => 'Turks ve Caicos Adaları']],
            ['iso' => 'TV', 'tr' => ['name' => 'Tuvalu']],
            ['iso' => 'TM', 'tr' => ['name' => 'Türkmenistan']],
            ['iso' => 'UG', 'tr' => ['name' => 'Uganda']],
            ['iso' => 'UA', 'tr' => ['name' => 'Ukrayna']],
            ['iso' => 'OM', 'tr' => ['name' => 'Umman']],
            ['iso' => 'UY', 'tr' => ['name' => 'Uruguay']],
            ['iso' => 'VU', 'tr' => ['name' => 'Vanuatu']],
            ['iso' => 'VA', 'tr' => ['name' => 'Vatikan']],
            ['iso' => 'VE', 'tr' => ['name' => 'Venezuela']],
            ['iso' => 'VN', 'tr' => ['name' => 'Vietnam']],
            ['iso' => 'WF', 'tr' => ['name' => 'Wallis ve Futuna']],
            ['iso' => 'YE', 'tr' => ['name' => 'Yemen']],
            ['iso' => 'NC', 'tr' => ['name' => 'Yeni Kaledonya']],
            ['iso' => 'NZ', 'tr' => ['name' => 'Yeni Zelanda']],
            ['iso' => 'GR', 'tr' => ['name' => 'Yunanistan']],
            ['iso' => 'ZM', 'tr' => ['name' => 'Zambiya']],
            ['iso' => 'ZW', 'tr' => ['name' => 'Zimbabve']],
            ['iso' => 'TD', 'tr' => ['name' => 'Çad']],
            ['iso' => 'CZ', 'tr' => ['name' => 'Çek Cumhuriyeti']],
            ['iso' => 'CN', 'tr' => ['name' => 'Çin']],
            ['iso' => 'UZ', 'tr' => ['name' => 'Özbekistan']],
            ['iso' => 'JO', 'tr' => ['name' => 'Ürdün']],
            ['iso' => 'VG', 'tr' => ['name' => 'İngiliz Virgin Adaları']],
            ['iso' => 'IR', 'tr' => ['name' => 'İran']],
            ['iso' => 'IE', 'tr' => ['name' => 'İrlanda']],
            ['iso' => 'ES', 'tr' => ['name' => 'İspanya']],
            ['iso' => 'IL', 'tr' => ['name' => 'İsrail']],
            ['iso' => 'SE', 'tr' => ['name' => 'İsveç']],
            ['iso' => 'CH', 'tr' => ['name' => 'İsviçre']],
            ['iso' => 'IT', 'tr' => ['name' => 'İtalya']],
            ['iso' => 'IS', 'tr' => ['name' => 'İzlanda']],
            ['iso' => 'CL', 'tr' => ['name' => 'Şili']]
        ];

        \DB::table('localization__countries')->truncate();
        \DB::table('localization__country_translations')->truncate();

        foreach ($countries as $country) {
            $this->country->create($country);
        }
    }
}
